server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 1800
management:
  security:
    enabled: false
security:
  user:
    name: admin
    password: cfmysqlweb
  basic:
    enabled: true
  sessions: never
