server:
  error:
    whitelabel:
      enabled: false
  session:
    timeout: 1800
security:
  user:
    name: admin
    password: cfmysqlweb
  basic:
    enabled: true


#server.session.timeout= # Session timeout in seconds.
